# Generated by Django 4.2.3 on 2023-12-24 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0004_alter_category_options_remove_category_sort_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dish',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='dish',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
